// CONSTANTS FOR CLASSIC PONG
export const CLASSIC_PONG_WIDTH = 800;
export const CLASSIC_PONG_HEIGHT = 600;
export const CLASSIC_PONG_PAD_WIDTH = 15;
export const CLASSIC_PONG_PAD_HEIGHT = 100;
export const CLASSIC_PONG_PAD_SPEED = 10;
export const CLASSIC_PONG_BALL_RADIUS = 5;
export const CLASSIC_PONG_BALL_SPEED = 5;

// CONSTANTS FOR SPATIAL PONG
export const SPATIAL_PONG_RADIUS = 132;
export const SPATIAL_PONG_PAD_RADIUS = 122;
export const SPATIAL_PONG_PAD_HEIGHT = Math.PI / 6;
export const SPATIAL_PONG_PAD_SPEED = 0.04;
export const SPATIAL_PONG_BALL_RADIUS = 5;
export const SPATIAL_PONG_BALL_SPEED = 3;

// CONSTANT FOR BLACKHOLE
export const SPATIAL_BLACKHOLE_RADIUS = 5;

// REFRESH RATE / TICK RATE
export const TICK_RATE = 1000 / 60;

// SCORE LIMITS
export const CLASSIC_PONG_SCORE_LIMIT = 5/*5*/;

export const START_DELAY = 5000;